<?php

/**
 * @file
 * Provides hook implementations for Layout Builder.
 */

/**
 * Implements hook_help().
 */
function layout_builder_help($route_name) {
  switch ($route_name) {
    case 'help.page.layout_builder':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Layout Builder provides layout building utility, surprisingly.') . '</p>';
      $output .= '<p>' . t('For more information, see the <a href=":layout-builder-documentation">online documentation for the Layout Builder module</a>.', [':layout-builder-documentation' => 'https://www.drupal.org/docs/8/core/modules/layout_builder']) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_contextual_links_view_alter().
 *
 * Change Configure Blocks into off_canvas links.
 */
function layout_builder_contextual_links_view_alter(&$element, $items) {
  $attach_lib = FALSE;
  $links = [
    'layout-builder-block-configure',
    'layout-builder-block-delete',
    'layout-builder-block-visibility'
  ];
  foreach ($links as $link) {
    if (isset($element['#links'][$link])) {
      $attributes = [
        'class' => ['use-ajax'],
        'data-dialog-type' => 'dialog',
        'data-dialog-renderer' => 'off_canvas',
      ];
      /** @var \Drupal\Core\Url $url */
      $url = $element['#links'][$link]['url'];
      $url_attributes = $url->getOption('attributes');
      $url_attributes = $url_attributes ? $url_attributes += $attributes : $attributes;
      $url->setOption('attributes', $url_attributes);
      $attach_lib = TRUE;
    }
  }

  if ($attach_lib) {
    $element['#attached']['library'][] = 'outside_in/drupal.off_canvas';
  }
}
